spring:
  application:
    name: debate-summary
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mariadb://localhost:3306/ttokcheong-debate-summary}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      platform: mariadb